spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/propertydb}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:aman@123}
spring.jpa.hibernate.ddl-auto=update
